name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on: windows-latest
    
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - name: win-32
            target: i686-pc-windows-msvc
            artifact_name: takure_32
          - name: win-64
            target: x86_64-pc-windows-msvc
            artifact_name: takure_64

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Add build target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Copy .toml file
        run: cp takure.toml target/${{ matrix.target }}/release/

      - name: Upload build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            target/${{ matrix.target }}/release/takure.dll
            target/${{ matrix.target }}/release/takure.toml

  release:
    name: Upload release artifacts
    needs: build
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Download win-32 build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          name: takure_32
          path: artifacts/takure_32

      - name: Download win-64 build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          name: takure_64
          path: artifacts/takure_64

      - name: Zip builds
        shell: pwsh
        run: |
          Compress-Archive -Path artifacts/takure_32/* -DestinationPath takure_32.zip
          Compress-Archive -Path artifacts/takure_64/* -DestinationPath takure_64.zip

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 #v3.0.3
        with:
          files: |
            takure_32.zip
            takure_64.zip
